# coding: utf-8

"""
    Hermeum Agent Plugin API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_client.models.agent_session_agent_session_events_request_events_inner_one_of1_assistant import AgentSessionAgentSessionEventsRequestEventsInnerOneOf1Assistant
from openapi_client.models.agent_session_agent_session_events_request_events_inner_one_of1_cost import AgentSessionAgentSessionEventsRequestEventsInnerOneOf1Cost
from openapi_client.models.agent_session_agent_session_events_request_events_inner_one_of1_moa_references_inner import AgentSessionAgentSessionEventsRequestEventsInnerOneOf1MoaReferencesInner
from openapi_client.models.agent_session_agent_session_events_request_events_inner_one_of1_usage import AgentSessionAgentSessionEventsRequestEventsInnerOneOf1Usage
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AgentSessionAgentSessionEventsRequestEventsInnerOneOf1(BaseModel):
    """
    AgentSessionAgentSessionEventsRequestEventsInnerOneOf1
    """ # noqa: E501
    event_id: StrictStr = Field(alias="eventId")
    type: StrictStr
    timestamp: StrictStr
    provider: StrictStr
    model: StrictStr
    api_mode: StrictStr = Field(alias="apiMode")
    usage: AgentSessionAgentSessionEventsRequestEventsInnerOneOf1Usage
    cost: AgentSessionAgentSessionEventsRequestEventsInnerOneOf1Cost
    assistant: AgentSessionAgentSessionEventsRequestEventsInnerOneOf1Assistant
    turn_id: Optional[StrictStr] = Field(default=None, alias="turnId")
    duration_s: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="durationS")
    finish_reason: Optional[StrictStr] = Field(default=None, alias="finishReason")
    moa_references: Optional[List[AgentSessionAgentSessionEventsRequestEventsInnerOneOf1MoaReferencesInner]] = Field(default=None, alias="moaReferences")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["eventId", "type", "timestamp", "provider", "model", "apiMode", "usage", "cost", "assistant", "turnId", "durationS", "finishReason", "moaReferences"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['llm_call']):
            raise ValueError("must be one of enum values ('llm_call')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgentSessionAgentSessionEventsRequestEventsInnerOneOf1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of usage
        if self.usage:
            _dict['usage'] = self.usage.to_dict()
        # override the default output from pydantic by calling `to_dict()` of cost
        if self.cost:
            _dict['cost'] = self.cost.to_dict()
        # override the default output from pydantic by calling `to_dict()` of assistant
        if self.assistant:
            _dict['assistant'] = self.assistant.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in moa_references (list)
        _items = []
        if self.moa_references:
            for _item_moa_references in self.moa_references:
                _items.append(_item_moa_references.to_dict() if _item_moa_references is not None else None)
            _dict['moaReferences'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgentSessionAgentSessionEventsRequestEventsInnerOneOf1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "eventId": obj.get("eventId"),
            "type": obj.get("type"),
            "timestamp": obj.get("timestamp"),
            "provider": obj.get("provider"),
            "model": obj.get("model"),
            "apiMode": obj.get("apiMode"),
            "usage": AgentSessionAgentSessionEventsRequestEventsInnerOneOf1Usage.from_dict(obj["usage"]) if obj.get("usage") is not None else None,
            "cost": AgentSessionAgentSessionEventsRequestEventsInnerOneOf1Cost.from_dict(obj["cost"]) if obj.get("cost") is not None else None,
            "assistant": AgentSessionAgentSessionEventsRequestEventsInnerOneOf1Assistant.from_dict(obj["assistant"]) if obj.get("assistant") is not None else None,
            "turnId": obj.get("turnId"),
            "durationS": obj.get("durationS"),
            "finishReason": obj.get("finishReason"),
            "moaReferences": [AgentSessionAgentSessionEventsRequestEventsInnerOneOf1MoaReferencesInner.from_dict(_item) for _item in obj["moaReferences"]] if obj.get("moaReferences") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


