/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './client/ui/routes/__root'
import { Route as IndexRouteImport } from './client/ui/routes/index'
import { Route as SigninRouteImport } from './client/ui/routes/signin'
import { Route as AgentsIndexRouteImport } from './client/ui/routes/agents/index'
import { Route as AgentsIdRouteImport } from './client/ui/routes/agents/$id'
import { Route as AgentsNewRouteImport } from './client/ui/routes/agents/new'
import { Route as SharedEnvSetsIndexRouteImport } from './client/ui/routes/shared-env-sets/index'
import { Route as SharedEnvSetsIdRouteImport } from './client/ui/routes/shared-env-sets/$id'
import { Route as AgentsIdIndexRouteImport } from './client/ui/routes/agents/$id/index'
import { Route as AgentsIdEditRouteImport } from './client/ui/routes/agents/$id/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/agents/$id',
  path: '/agents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsNewRoute = AgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedEnvSetsIndexRoute = SharedEnvSetsIndexRouteImport.update({
  id: '/shared-env-sets/',
  path: '/shared-env-sets/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedEnvSetsIdRoute = SharedEnvSetsIdRouteImport.update({
  id: '/shared-env-sets/$id',
  path: '/shared-env-sets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIdIndexRoute = AgentsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentsIdRoute,
} as any)
const AgentsIdEditRoute = AgentsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AgentsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/agents/$id': typeof AgentsIdRouteWithChildren
  '/agents/new': typeof AgentsNewRoute
  '/shared-env-sets/$id': typeof SharedEnvSetsIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/shared-env-sets/': typeof SharedEnvSetsIndexRoute
  '/agents/$id/edit': typeof AgentsIdEditRoute
  '/agents/$id/': typeof AgentsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/agents/new': typeof AgentsNewRoute
  '/shared-env-sets/$id': typeof SharedEnvSetsIdRoute
  '/agents': typeof AgentsIndexRoute
  '/shared-env-sets': typeof SharedEnvSetsIndexRoute
  '/agents/$id/edit': typeof AgentsIdEditRoute
  '/agents/$id': typeof AgentsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/agents/$id': typeof AgentsIdRouteWithChildren
  '/agents/new': typeof AgentsNewRoute
  '/shared-env-sets/$id': typeof SharedEnvSetsIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/shared-env-sets/': typeof SharedEnvSetsIndexRoute
  '/agents/$id/edit': typeof AgentsIdEditRoute
  '/agents/$id/': typeof AgentsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/agents/$id'
    | '/agents/new'
    | '/shared-env-sets/$id'
    | '/agents/'
    | '/shared-env-sets/'
    | '/agents/$id/edit'
    | '/agents/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/agents/new'
    | '/shared-env-sets/$id'
    | '/agents'
    | '/shared-env-sets'
    | '/agents/$id/edit'
    | '/agents/$id'
  id:
    | '__root__'
    | '/'
    | '/signin'
    | '/agents/$id'
    | '/agents/new'
    | '/shared-env-sets/$id'
    | '/agents/'
    | '/shared-env-sets/'
    | '/agents/$id/edit'
    | '/agents/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SigninRoute: typeof SigninRoute
  AgentsIdRoute: typeof AgentsIdRouteWithChildren
  AgentsNewRoute: typeof AgentsNewRoute
  SharedEnvSetsIdRoute: typeof SharedEnvSetsIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  SharedEnvSetsIndexRoute: typeof SharedEnvSetsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/agents/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/new': {
      id: '/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AgentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared-env-sets/': {
      id: '/shared-env-sets/'
      path: '/shared-env-sets'
      fullPath: '/shared-env-sets/'
      preLoaderRoute: typeof SharedEnvSetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared-env-sets/$id': {
      id: '/shared-env-sets/$id'
      path: '/shared-env-sets/$id'
      fullPath: '/shared-env-sets/$id'
      preLoaderRoute: typeof SharedEnvSetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$id/': {
      id: '/agents/$id/'
      path: '/'
      fullPath: '/agents/$id/'
      preLoaderRoute: typeof AgentsIdIndexRouteImport
      parentRoute: typeof AgentsIdRoute
    }
    '/agents/$id/edit': {
      id: '/agents/$id/edit'
      path: '/edit'
      fullPath: '/agents/$id/edit'
      preLoaderRoute: typeof AgentsIdEditRouteImport
      parentRoute: typeof AgentsIdRoute
    }
  }
}

interface AgentsIdRouteChildren {
  AgentsIdEditRoute: typeof AgentsIdEditRoute
  AgentsIdIndexRoute: typeof AgentsIdIndexRoute
}

const AgentsIdRouteChildren: AgentsIdRouteChildren = {
  AgentsIdEditRoute: AgentsIdEditRoute,
  AgentsIdIndexRoute: AgentsIdIndexRoute,
}

const AgentsIdRouteWithChildren = AgentsIdRoute._addFileChildren(
  AgentsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SigninRoute: SigninRoute,
  AgentsIdRoute: AgentsIdRouteWithChildren,
  AgentsNewRoute: AgentsNewRoute,
  SharedEnvSetsIdRoute: SharedEnvSetsIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  SharedEnvSetsIndexRoute: SharedEnvSetsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
