{{- if include "hermeum.createSecret" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hermeum.secretName" . }}
  labels:
    {{- include "hermeum.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.secrets.databaseUrl | quote }}
  better-auth-secret: {{ .Values.secrets.betterAuthSecret | quote }}
  {{- with .Values.secrets.betterAuthUrl }}
  better-auth-url: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.smtpUrl }}
  smtp-url: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.openaiBaseUrl }}
  openai-base-url: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.openaiApiKey }}
  openai-api-key: {{ . | quote }}
  {{- end }}
{{- end -}}