/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SandboxesIndexRouteImport } from './routes/sandboxes/index'
import { Route as SandboxesNameRouteImport } from './routes/sandboxes/$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxesIndexRoute = SandboxesIndexRouteImport.update({
  id: '/sandboxes/',
  path: '/sandboxes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxesNameRoute = SandboxesNameRouteImport.update({
  id: '/sandboxes/$name',
  path: '/sandboxes/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sandboxes/$name': typeof SandboxesNameRoute
  '/sandboxes/': typeof SandboxesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sandboxes/$name': typeof SandboxesNameRoute
  '/sandboxes': typeof SandboxesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sandboxes/$name': typeof SandboxesNameRoute
  '/sandboxes/': typeof SandboxesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sandboxes/$name' | '/sandboxes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sandboxes/$name' | '/sandboxes'
  id: '__root__' | '/' | '/sandboxes/$name' | '/sandboxes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SandboxesNameRoute: typeof SandboxesNameRoute
  SandboxesIndexRoute: typeof SandboxesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandboxes/': {
      id: '/sandboxes/'
      path: '/sandboxes'
      fullPath: '/sandboxes/'
      preLoaderRoute: typeof SandboxesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandboxes/$name': {
      id: '/sandboxes/$name'
      path: '/sandboxes/$name'
      fullPath: '/sandboxes/$name'
      preLoaderRoute: typeof SandboxesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SandboxesNameRoute: SandboxesNameRoute,
  SandboxesIndexRoute: SandboxesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
